apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.labels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.api.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: restapi
              containerPort: {{ .Values.api.service.ports.restapi.containerPort }}
              protocol: {{ .Values.api.service.ports.restapi.protocol }}
            - name: websocket
              containerPort: {{ .Values.api.service.ports.websocket.containerPort }}
              protocol: {{ .Values.api.service.ports.websocket.protocol }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          env:
            - name: FL_ORCHESTRATOR_URL
              value: "http://{{ include "orchestrator.fullname" . }}:{{ .Values.orchestrator.service.ports.webservice.containerPort }}"
          {{- with .Values.api.envVars }}
            - name: NODE_ENV
              value: {{ .NODE_ENV | quote }}
            - name: FL_REPOSITORY_URL
              value: {{ .FL_REPOSITORY_URL | quote }}
          {{- end }}
