apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - name: port1
      port: {{ .Values.webapp.service.ports.port1.port }}
      targetPort: {{ .Values.webapp.service.ports.port1.targetPort }}
      protocol: {{ .Values.webapp.service.ports.port1.protocol }}
      {{- if and (or (eq .Values.webapp.service.type "NodePort") (eq .Values.webapp.service.type "LoadBalancer")) (not (empty .Values.webapp.service.ports.port1.nodePort)) }}
      nodePort: {{ .Values.webapp.service.ports.port1.nodePort }}
      {{- end }}
  selector:
    {{- include "webapp.selectorLabels" . | nindent 4 }}
